name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env: 
  EB_PACKAGE_S3_BUCKET-NAME : "webapplicationmipi"
  EB_APPLICATION_NAME       : "mirceabularga.com"
  EB_ENVIROMENT_NAME        : "Mirceabulargacom-env"
  DEPLOY_PACKAGE_NAME       : "mirceabularga_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"

on:
  push:
    branches: 
      - main
      
jobs:
  CI-Job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Clone Repositories
      uses: actions/checkout@v1
      
    - name: Create ZIP deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESSS_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}
      
    - name: Copy package to S3 Bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET-NAME }}/
      
